import { JewelryItem } from "@/types";

export const jewelryItems: JewelryItem[] = [
    {
        id: "1",
        name: "The Eternal Solitaire",
        image: "/images/rings/solitaire-round.png",
        shape: "Round",
        carat: "1 - 2 carat",
        goldColor: "White Gold",
        style: "Solitaire",
        price: 125000,
        productUrl: "https://shopify.com/products/eternal-solitaire",
    },
    {
        id: "2",
        name: "Midnight Halo Oval",
        image: "/images/rings/halo-oval.png",
        shape: "Oval",
        carat: "1 - 2 carat",
        goldColor: "Yellow Gold",
        style: "Halo",
        price: 145000,
        productUrl: "https://shopify.com/products/midnight-halo-oval",
    },
    {
        id: "3",
        name: "Royal Emerald Cut",
        image: "/images/rings/three-stone-emerald.png",
        shape: "Emerald",
        carat: "2 - 3 carat",
        goldColor: "White Gold",
        style: "Three Stone",
        price: 245000,
        productUrl: "https://shopify.com/products/royal-emerald-cut",
    },
    {
        id: "4",
        name: "Petite Pave Pear",
        image: "/images/rings/pave-pear.png",
        shape: "Pear",
        carat: "0.5 - 1 carat",
        goldColor: "Rose Gold",
        style: "Pave",
        price: 48000,
        productUrl: "https://shopify.com/products/petite-pave-pear",
    },
    {
        id: "5",
        name: "Luminous Hidden Halo",
        image: "/images/rings/hidden-halo-cushion.png",
        shape: "Cushion",
        carat: "1 - 2 carat",
        goldColor: "Yellow Gold",
        style: "Hidden Halo",
        price: 95000,
        productUrl: "https://shopify.com/products/luminous-hidden-halo",
    },
    {
        id: "6",
        name: "Majestic Princess Halo",
        image: "/images/rings/halo-princess.png",
        shape: "Princess",
        carat: "2 - 3 carat",
        goldColor: "White Gold",
        style: "Halo",
        price: 185000,
        productUrl: "https://shopify.com/products/majestic-princess-halo",
    },
    {
        id: "7",
        name: "Classic Solitaire Oval",
        image: "/images/rings/solitaire-oval.png",
        shape: "Oval",
        carat: "1 - 2 carat",
        goldColor: "Rose Gold",
        style: "Solitaire",
        price: 88000,
        productUrl: "https://shopify.com/products/classic-solitaire-oval",
    },
    {
        id: "8",
        name: "Vintage Three Stone",
        image: "/images/rings/three-stone-round.png",
        shape: "Round",
        carat: "2 - 3 carat",
        goldColor: "Yellow Gold",
        style: "Three Stone",
        price: 215000,
        productUrl: "https://shopify.com/products/vintage-three-stone",
    }
];
